// AUTHS
export const USER_LOADED_REQUEST = 'USER_LOADED_REQUEST';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAILURE = 'USER_LOADED_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const  REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const  LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT =  'LOGOUT';

// LOANS
export  const CREATE_NEW_LOAN_REQUEST = 'CREATE_NEW_LOAN_REQUEST';
export  const CREATE_NEW_LOAN_SUCCESS = 'CREATE_NEW_LOAN_SUCCESS';
export  const CREATE_NEW_LOAN_FAILURE = 'CREATE_NEW_LOAN_FAILURE';

export  const UPDATE_LOAN_BY_ID_REQUEST = 'UPDATE_LOAN_BY_ID_REQUEST';
export  const UPDATE_LOAN_BY_ID_SUCCESS = 'UPDATE_LOAN_BY_ID_SUCCESS';
export  const UPDATE_LOAN_BY_ID_FAILURE = 'UPDATE_LOAN_BY_ID_FAILURE';

export  const GET_LOAN_BY_ID_REQUEST = 'GET_LOAN_BY_ID_REQUEST';
export  const GET_LOAN_BY_ID_SUCCESS = 'GET_LOAN_BY_ID_SUCCESS';
export  const GET_LOAN_BY_ID_FAILURE = 'GET_LOAN_BY_ID_FAILURE';

export  const DELETE_LOAN_BY_ID_REQUEST = 'DELETE_LOAN_BY_ID_REQUEST';
export  const DELETE_LOAN_BY_ID_SUCCESS = 'DELETE_LOAN_BY_ID_SUCCESS';
export  const DELETE_LOAN_BY_ID_FAILURE = 'DELETE_LOAN_BY_ID_FAILURE';

export  const GET_ALL_LOANS_REQUEST = 'GET_ALL_LOANS_REQUEST';
export  const GET_ALL_LOANS_SUCCESS = 'GET_ALL_LOANS_SUCCESS';
export  const GET_ALL_LOANS_FAILURE = 'GET_ALL_LOANS_FAILURE';
